Donation feature component
grundeinkommensbuero/website pull request #166
Opened 2020-11-09 15:00 UTC by schaerta

Credit to @felixbuchholz

2020-11-09 15:06 UTC, felixbuchholz commented on src/components/Forms/DonationForm/index.js
> +    formData = JSON.parse(JSON.stringify(values));
Rein stilistischer Vorschlag: 
`formData = {...values}`
Weil wir das so eigentlich immer verwenden (hatte ich so aus alter Gewohnheit geschrieben)

2020-11-09 15:11 UTC, schaerta commented on src/components/Forms/DonationForm/index.js
> +    formData = JSON.parse(JSON.stringify(values));
Gibt es nicht so ein neues Feature hier, dass man im Kommentar einen Vorschlag macht und den dann direkt übernehmen kann? Das könnten wir gerade mal probieren.

2020-11-11 12:28 UTC, Valioesi requested changes
Other than the missing loading state and one other thing, it looks good. :)
Fyi usually FinallyMessage is used for loading state.

One other thing: The privacy and sepa boolean are sent to the backend and saved in the db because I actually don't strip anything out of the donation object in the backend after checking if everything needed is there. Should I strip it in the backend or should we strip sepa and privacy in the frontend? Or both? :D

2020-11-11 12:28 UTC, Valioesi commented on src/components/Forms/DonationForm/index.js
> +      {hasDonated && !donationError && (
Does it maybe make sense here to use the FinallyMessage component? Maybe not, since the whole form is inside of a container anyway.

2020-11-13 15:10 UTC, felixbuchholz approved these changes
Navigation mit Tab funktioniert super! Und das Beibehalten der Daten auch. Konfetti sieht gut aus! Wenn man am Ende auf "Zurück zum Formular" geht, bleiben die Daten auch erhalten. Da könnte man vielleicht noch mal Tester:innen fragen, ob sie das so erwarten würden.

2020-11-23 11:35 UTC, Valioesi approved these changes
Top, der Ladezustand und das Konfetti sind super und wegen mir ist es ready to merge. Müssen dann nur noch den Termin mit Max abwarten...

2020-11-23 11:37 UTC, merged