Accessibility improvements
grundeinkommensbuero/website pull request #344
Opened 2021-09-23 16:32 UTC by schaerta

Some improvements after user tests.
Note: The linter complained when I tried to use an invisible link that just serves as a button. I also googled around and it just seems like a bad way of solving the problem. So I added an invisible heading instead, that should make the signup easier to find.
If you can think of anything else to add to improve a11y, please let me know!

2021-09-23 17:19 UTC, Valioesi requested changes
ariaLabel instead of aria-label

2021-09-23 17:19 UTC, Valioesi commented on src/components/TickerToSignup/SignupButton/index.js
> +          ariaLabel="Anmelden"
Heißt es nicht aria-label?

2021-09-29 09:39 UTC, schaerta commented on src/components/TickerToSignup/SignupButton/index.js
> +          ariaLabel="Anmelden"
Oh, da hast du wohl recht. Dachte, es wäre camel case, wie sonst auch bei JSX. Habe es angepasst.

2021-09-30 13:40 UTC, nmauersberg approved these changes
Super cool, thank you! <3

2021-10-04 07:43 UTC, Valioesi approved these changes
Thank you! :)

2021-10-04 07:53 UTC, merged